stages:
  - test

test-fedora-latest:
  stage: test
  image: registry.gitlab.gnome.org/sthursfield/tracker-oci-images/amd64/fedora:latest

  script:
    - su tracker -c 'mkdir build'
    - su tracker -c 'cd build; meson ..'
    - su tracker -c 'cd build; ninja'
    - |
      # Remove the many "CI_" variables from the environment. Meson dumps the
      # whole environment for every failed test, and that gives a whole
      # screenful of junk each time unless we strip these.
      unset $(env|grep -o '^CI_[^=]*')

      su tracker -c 'cd build; LANG=en_US.UTF8 dbus-run-session -- meson test --print-errorlogs'
