stages:
  - test

test-autotools-fedora28:
  stage: test
  image: fedora:28

  before_script:
    - dnf install -y 'dnf-command(builddep)' redhat-rpm-config libseccomp-devel make
    - dnf builddep -y tracker

  script:
    - ./autogen.sh --disable-functional-tests
    - make
    - make check
