stages:
  - test

fedora:rawhide:
    image: fedora:rawhide
    stage: test
    before_script:
        - dnf update -y --nogpgcheck
        - dnf install -y 'dnf-command(builddep)' redhat-rpm-config libseccomp-devel gcovr --nogpgcheck
        - dnf builddep -y tracker --nogpgcheck
    script:
        - meson _build .
        - cd _build
        - |
          # Remove the many "CI_" variables from the environment. Meson dumps the
          # whole environment for every failed test, and that gives a whole
          # screenful of junk each time unless we strip these.
          unset $(env|grep -o '^CI_[^=]*')
        - ninja test
